### ISSUE TITLE
why I can not run the code successfully?

### ISSUE THREAD

**Issue by leoliumessi** [isaac-sim/OmniIsaacGymEnvs#126]
I run the tran.py code, but I always face the same problem that the platform cannot run successfully.
![0241a2b62651ac0946dce68d0ff42e2](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/103296010/f72452a9-9cad-4492-b506-8bf2b36129a8)

**Comment by eferreirafilho** [comment]
Please paste the full command you have used
